export * from './arrows';
export * from './brand';
export * from './building';
export * from './currency';
export * from './graph';
export * from './hand';
export * from './mail';
export * from './media';
export * from './settings';
export * from './technology';
// export * from './typography';
export * from './vowel';
export * from './weather';
export * from './others';
export * from './shape';
export * from './math';
